application: songsofthevictorians
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /data
  static_dir: data

- url: /static
  static_dir: static

- url: /.*
  script: main.app

# - url: /
#   static_dir: site

libraries:
- name: lxml
  version: latest